services:
  kokoro-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      # Optional: Mount a volume for model cache to persist downloads
      - huggingface_cache:/home/appuser/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Apple Silicon optimized version
  # kokoro-streamer-m1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.apple-silicon
  #     platforms:
  #       - linux/arm64
  #   ports:
  #     - "7860:7860"
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - GRADIO_SERVER_NAME=0.0.0.0
  #     - GRADIO_SERVER_PORT=7860
  #   volumes:
  #     # Optional: Mount a volume for model cache to persist downloads
  #     - huggingface_cache:/home/appuser/.cache/huggingface
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:7860/"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s
  #   profiles:
  #     - apple-silicon

volumes:
  huggingface_cache: 